/* generated by cppy on 2016-12-09 17:11:37.069497 */
    bool initialize_class_Abel(void* pyObject_module);
    bool initialize_class_Kain(void* pyObject_module);
    /* Call this before Py_Initialize() */
    bool initialize_module_example();
