/* generated by cppy on 2016-12-09 16:11:53.604077 */
    bool initialize_class_Abel(void* pyObject_module);
    bool initialize_class_Kain(void* pyObject_module);
    /* Call this before Py_Initialize() */
    bool initialize_module_test_module();
